### ISSUE TITLE
Undefined values displayed in matrix sometimes

### ISSUE THREAD

**Issue by Ezio-Sarthak** [Shashwat-Garg/bingo-multiplayer#2]
The following undefined cell error is encountered for a matrix sometimes.
![Undefined-cell](https://user-images.githubusercontent.com/55916430/84052643-79338c80-a9ce-11ea-8adb-b467e56c8eea.png)

**Comment by Shashwat-Garg** [comment]
This was because of wrong random array generation code. Fixed, hence closing.
